size_side: 0.36
ropod_length: 0.65
feeler_size: 1.0
feeler_size_steering: 1.0
env_tctw_size: 0.05
env_trns_size: 0.2
carrot_length_feeler_offset: 0.5
d_ax: 1.045
size_rear: 0.1
env_trns_size_cornering: 0.45
v_cruising: 0.6 # 1.2
v_inter_turning: 0.3 # 0.5
v_steersaturation: 0.2 # 0.4
v_overtake: 1.0
delta_dot_limit: 0.5
a_max: 0.5
v_obs_overtake_max: 0.1
min_dist_to_overtake: 3.0
start_steering_early_right: 0.5 # 0.5
start_steering_early_left: 0.3 # 0.6
rotated_enough_thres: 1.05
t_min_pred: 10.0
t_pred_wall_collision: 5.0
t_pred_obs_collision: 4.0
cutoff_freq: 1.0
obs_avoid_margin: 0.1
obs_avoid_margin_front: 0.15
dilate_ropod_aligning: 0.9
reached_target_threshold: 2.0
entry_length: 2.0
sharp_angle_threshold: 0.1
is_load_attached: True
